#!/bin/bash
row=$1
echo $row | grep -iq '^[0-9]$'
if [ $? -eq 0 ] 
then
    line=$((row+1))
    devicename=$(adb devices|sed -n "${line}p"|awk '{print $1}')
    if [ -z $2 ]
    then
        echo $devicename
    else
        adb -s $devicename $2 $3 $4 $5 $6
    fi  
elif [ $1 == 'd' ]
then
    adb devices
elif [ $1 == 'uninstall' ]
then
    apkname=$2
    packagename=`aapt d badging $apkname | sed -n "1p"|cut -d\' -f2`
    adb uninstall $packagename
elif [ $1 == 'install' ]
then
    apkname=$2
    sadb u $apkname
    adb install $apkname
else
    adb $1 $2 $3 $4
fi
