#!/bin/bash
row=$1
echo $row | grep -iq '^[0-9]$'
if [ $? -eq 0 ]
then
    line=$((row+1))
    devicename=$(adb devices|sed -n "${line}p"|awk '{print $1}')
    if [ -z $2 ]
    then
        echo $devicename
    else
        sadb $2 $3 $4 $5 $6 -s $devicename 
    fi  
elif [ $1 == 'd' ]
then
    adb devices
elif [ $1 == 'uninstall' ]
then
    num=$#
    flag=$(eval echo "\$$((num-1))")
    apkname=$2
    packagename=`aapt d badging $apkname | sed -n "1p"|cut -d\' -f2`

    if [ $flag == "-s" ]
    then
        devicename=$(eval echo "\$$num")
        echo adb -s $devicename uninstall $packagename
        adb -s $devicename  uninstall $packagename
    else
        adb uninstall $packagename
    fi  
elif [ $1 == 'install' ]
then
    num=$#
    flag=$(eval echo "\$$((num-1))")

    apkname=$2
    if [ $flag == "-s" ]
    then
        devicename=$(eval echo "\$$num")
        sadb uninstall $apkname $3 $4 $5 $6 $7 $8 & adb -s $devicename  install $apkname 
        #adb -s $devicename  install $apkname 
    else        
        adb uninstall $apkname $3 $4 $5 $6 $7 $8
        adb  install $apkname $3 $4 $5 $6 $7 $8
    fi  
else
    adb $1 $2 $3 $4
fi
